### ISSUE TITLE
Request: Inherit names between Components and Bodies

### ISSUE THREAD

**Issue by Specimen** [thomasa88/DirectName#10]
Suggestion/Request

I've been looking for an easy solution for naming bodies for OBJ exports (only body names are exported).
I would be perfectly happy if if bodies had the same name as the parent component plus an incremental number at the end for multiple bodies.

So my suggestion considering how this add on works would be to have the option for the naming box of a new body to inherit the component name.

**Comment by thomasa88** [comment]
Hi, I just published [version 1.4.1 on Github](https://github.com/thomasa88/DirectName/releases/tag/v1.4.1), where I have added this feature. A new installer will hopefully appear in the Autodesk app store in 1-2 weeks.

**Comment by Specimen** [comment]
> Hi, I just published [version 1.4.1 on Github](https://github.com/thomasa88/DirectName/releases/tag/v1.4.1), where I have added this feature. A new installer will hopefully appear in the Autodesk app store in 1-2 weeks.

Thank you so much for this! Can't wait to try it.
