### ISSUE TITLE
Direct Name Failing when creating sheet metal flat pattern

### ISSUE THREAD

**Issue by patl1** [thomasa88/DirectName#11]
When I try and create a flat pattern in sheet metal, it errors out. I am using latest version of F360

**Comment by thomasa88** [comment]
Hi, it seems to be a bug when accessing app_.activeProduct in Fusion. I changed it to check design.activeProduct instead and now it seems that the errors are gone. There is no name prompting in the flat pattern editor, but at least there are no errors.

Please try this release: https://github.com/thomasa88/DirectName/releases/download/v1.3.1/DirectName-v1.3.1.zip

Either replace the existing installed DirectName.py file or uninstall the installed version and follow these instructions for "installing" the zip file: https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/How-to-install-an-ADD-IN-and-Script-in-Fusion-360.html 

I will send an update to the app store once I have confirmation that it works :).


Original report: https://apps.autodesk.com/FUSION/en/Detail/Index?id=7497198800232664541&appLang=en&os=Mac#9035463451030799641

**Comment by patl1** [comment]
Thanks Thomas. I am not getting the errors anymore. Thanks for your time and effort to correct it. I really like the add-in.

Pat

**Comment by thomasa88** [comment]
Thanks for the confirmation and glad to hear that you like the add-in!

I will submit the updated version to Autodesk.
