### ISSUE TITLE
Suggestion - Preselect default text in name field

### ISSUE THREAD

**Issue by Scott216** [thomasa88/DirectName#13]
It would be nice if the text for the name was preselected/highlighted.  This would save me the step of using my mouse to select the default text before typing over it.  If the default name was preselected, I could just type the name I wanted.

**Comment by thomasa88** [comment]
Hi, are you using Mac or Windows?

A workaround, that works on Windows at least, is to press `Tab` to focus the input box.

**Comment by thomasa88** [comment]
The Fusion APIs does not allow for pre-selecting the textbox. An ugly workaround might be for the add-in to send a Tab key to Windows. I might look into this.

Does pressing Tab work for you, to get the text selected? Otherwise, the change would be moot 😅

**Comment by Scott216** [comment]
Yes, pressing tab does work for me

**Comment by thomasa88** [comment]
I have uploaded a beta release here: https://github.com/thomasa88/DirectName/releases/download/v1.4.0-beta.1/DirectName-v1.4.0-beta.1.zip

Please try it out and see if it works for you.

If you have installed the add-in using the installer from Autodesk, you will need to uninstall the add-in using Add/Remove programs before "installing" the Zip file.

Follow the instructions here to unpack the addin zip file to the correct location:
https://knowledge.autodesk.com/support/fusion-360/troubleshooting/caas/sfdcarticles/sfdcarticles/How-to-install-an-ADD-IN-and-Script-in-Fusion-360.html

**Comment by Scott216** [comment]
I installed the beta.  The preselect text works for me.   Thanks!

**Comment by thomasa88** [comment]
Thanks for the feedback!

I just published [version 1.4.1 on Github](https://github.com/thomasa88/DirectName/releases/tag/v1.4.1), where I have added this feature. A new installer will hopefully appear in the Autodesk app store in 1-2 weeks.
