### ISSUE TITLE
 problem with Installer on osx

### ISSUE THREAD

**Issue by SkylarSouthard** [thomasa88/DirectName#2]
After running the installer there was no Direct name add-on in the add-on window, and there was no ad on in the ad on folder.

**Comment by thomasa88** [comment]
Hi, I have had big problems with the Mac installer that Autodesk creates. Not really being a Mac user myself, it's hard to know what goes wrong.

In this case it seems that the installer finished correctly?

Have you checked the Add-ins list in Fusion? TOOLS -> Add-ins -> Scripts and add-ins... and check the Add-ins tab.

I know that there historically have been two places where add-ins are installed, where the add-in installer chooses the more "secret" path. I think it might be symlink today, though.

If the add-in is not in the list, please try installing the zip file by the Installation instructions here: https://github.com/thomasa88/DirectName
