### ISSUE TITLE
Show renaming dialog when creating new component in Extrude

### ISSUE THREAD

**Issue by THEsutherland** [thomasa88/DirectName#3]
It would be neat if you could implement the same feature but for components. When extruding and selecting "New component", it would be nice to rename the component right away.

**Comment by thomasa88** [comment]
I remember not adding the naming feature when using the "New component" button, as that dialog already has a name field.

But this is a new use case. I'll have a look (when time permits).

**Comment by thomasa88** [comment]
Hi, I just published version 1.4.1 on Github, where I have added this feature. It will hopefully appear in the Autodesk app store in 1-2 weeks.
