### ISSUE TITLE
Add Description Field

### ISSUE THREAD

**Issue by troyostrander** [thomasa88/DirectName#4]
I could not imagine using Fusion without this plugin. What a time saver. We started making drawings and find the "description" field important but there is no name in there....Is it possible to add this to DirectName?

**Comment by thomasa88** [comment]
Hi, I have not used the Drawings environment that much. Could you provide some screenshots of this field and also when you expect DirectName to pop up?

Don't keep your hopes up though. Except for the Design workspace, the Fusion support for add-ins is very limited.

**Comment by troyostrander** [comment]
Hi,

I imagined that the "Description" field would added to the DirectName
prompt in the design workspace. As of now in Fusion, the Description field
can only be accessed Select Component, Right click, Properties. Since I
type the name of the feature once and copy and paste it for body name and
description, It would be so convenient if it could happen all in one place.

The description field change made in the design workspace gets pushed to
the drawing workspace.

See screenshots.

Best, Troy

**Comment by thomasa88** [comment]
Code note: Field: component.description

**Comment by thomasa88** [comment]
Hi, I just published [version 1.4.1 on Github](https://github.com/thomasa88/DirectName/releases/tag/v1.4.1), where I have added this feature. A new installer will hopefully appear in the Autodesk app store in 1-2 weeks.
